version: '3'

services:
  nginx:
    image: nginx
    container_name: temp_nginx_for_ssl_key
    volumes:
      - ${path_to_webroot}:/usr/share/nginx/html
      - ${path_to_save_ssl_key}:/etc/letsencrypt
    command: >
      bash -c "nginx 
      && apt-get -y install curl
      && curl --output /etc/letsencrypt/options-ssl-nginx.conf --url https://raw.githubusercontent.com/certbot/certbot/master/certbot-nginx/certbot_nginx/_internal/tls_configs/options-ssl-nginx.conf
      && openssl dhparam -out /etc/letsencrypt/ssl-dhparams.pem 2048"
    ports: 
      - 80:80
    
  certbot:
    depends_on:
      - nginx
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ${path_to_save_ssl_key}:/etc/letsencrypt
      - ${path_to_webroot}:/usr/share/nginx/html
    command: certonly --webroot --webroot-path=/usr/share/nginx/html --email ${DNS_email} --agree-tos --no-eff-email --force-renewal -d ${domain_name}